# Generated by Django 4.2.13 on 2024-06-26 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="object_id",
        ),
    ]
