# Generated by Django 4.2.13 on 2024-06-19 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_alter_recipe_category_alter_recipe_cover_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="user",
            new_name="author",
        ),
    ]
