# Generated by Django 4.2.13 on 2024-06-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0002_remove_tag_content_type_remove_tag_object_id"),
        ("recipes", "0003_alter_category_options_rename_user_recipe_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(to="tag.tag"),
        ),
    ]
